namespace DotNetAppPublisher.Services;

public sealed record PlatformProfile(
    string TargetFramework,
    string RuntimeIdentifier,
    bool SelfContained,
    bool PublishTrimmed,
    bool PublishAot,
    bool PublishReadyToRun,
    bool PublishSingleFile,
    bool UseAppHost,
    bool CreateMacAppBundle,
    bool CreateWindowsExecutable,
    bool BuildIpa,
    bool ArchiveOnBuild,
    bool RunAotCompilation,
    bool EnableProfiledAot,
    string AndroidLinkMode,
    string AndroidLinkTool,
    string AndroidDexTool,
    bool CreateMappingFile,
    bool EnableMultiDex,
    bool UseAapt2,
    bool EnableDesugar,
    bool IncludeApk,
    bool IncludeAab,
    string SignMode,
    string Configuration);

public static class PlatformDefaults
{
    public static PlatformProfile GetDefaults(string publishPlatform)
    {
        return publishPlatform switch
        {
            PublisherService.AndroidPlatform => new PlatformProfile(
                TargetFramework: "net10.0-android",
                RuntimeIdentifier: "android-arm64",
                SelfContained: true,
                PublishTrimmed: false,
                PublishAot: false,
                PublishReadyToRun: false,
                PublishSingleFile: true,
                UseAppHost: true,
                CreateMacAppBundle: true,
                CreateWindowsExecutable: true,
                BuildIpa: false,
                ArchiveOnBuild: true,
                RunAotCompilation: false,
                EnableProfiledAot: false,
                AndroidLinkMode: "None",
                AndroidLinkTool: "r8",
                AndroidDexTool: "d8",
                CreateMappingFile: false,
                EnableMultiDex: false,
                UseAapt2: true,
                EnableDesugar: true,
                IncludeApk: true,
                IncludeAab: false,
                SignMode: "Auto",
                Configuration: "Release"),

            PublisherService.MacOsPlatform => new PlatformProfile(
                TargetFramework: "net10.0",
                RuntimeIdentifier: "osx-arm64",
                SelfContained: true,
                PublishTrimmed: false,
                PublishAot: false,
                PublishReadyToRun: false,
                PublishSingleFile: true,
                UseAppHost: true,
                CreateMacAppBundle: true,
                CreateWindowsExecutable: true,
                BuildIpa: false,
                ArchiveOnBuild: true,
                RunAotCompilation: false,
                EnableProfiledAot: false,
                AndroidLinkMode: "None",
                AndroidLinkTool: "r8",
                AndroidDexTool: "d8",
                CreateMappingFile: false,
                EnableMultiDex: false,
                UseAapt2: true,
                EnableDesugar: true,
                IncludeApk: true,
                IncludeAab: false,
                SignMode: "Auto",
                Configuration: "Release"),

            PublisherService.WindowsPlatform => new PlatformProfile(
                TargetFramework: "net10.0-windows",
                RuntimeIdentifier: "win-x64",
                SelfContained: true,
                PublishTrimmed: false,
                PublishAot: false,
                PublishReadyToRun: false,
                PublishSingleFile: true,
                UseAppHost: true,
                CreateMacAppBundle: true,
                CreateWindowsExecutable: true,
                BuildIpa: false,
                ArchiveOnBuild: true,
                RunAotCompilation: false,
                EnableProfiledAot: false,
                AndroidLinkMode: "None",
                AndroidLinkTool: "r8",
                AndroidDexTool: "d8",
                CreateMappingFile: false,
                EnableMultiDex: false,
                UseAapt2: true,
                EnableDesugar: true,
                IncludeApk: true,
                IncludeAab: false,
                SignMode: "Auto",
                Configuration: "Release"),

            PublisherService.IosPlatform => new PlatformProfile(
                TargetFramework: "net10.0-ios",
                RuntimeIdentifier: "ios-arm64",
                SelfContained: true,
                PublishTrimmed: true,
                PublishAot: false,
                PublishReadyToRun: false,
                PublishSingleFile: true,
                UseAppHost: false,
                CreateMacAppBundle: true,
                CreateWindowsExecutable: true,
                BuildIpa: false,
                ArchiveOnBuild: true,
                RunAotCompilation: false,
                EnableProfiledAot: false,
                AndroidLinkMode: "None",
                AndroidLinkTool: "r8",
                AndroidDexTool: "d8",
                CreateMappingFile: false,
                EnableMultiDex: false,
                UseAapt2: true,
                EnableDesugar: true,
                IncludeApk: true,
                IncludeAab: false,
                SignMode: "Auto",
                Configuration: "Release"),

            PublisherService.LinuxPlatform => new PlatformProfile(
                TargetFramework: "net10.0",
                RuntimeIdentifier: "linux-x64",
                SelfContained: true,
                PublishTrimmed: false,
                PublishAot: false,
                PublishReadyToRun: false,
                PublishSingleFile: true,
                UseAppHost: true,
                CreateMacAppBundle: false,
                CreateWindowsExecutable: true,
                BuildIpa: false,
                ArchiveOnBuild: false,
                RunAotCompilation: false,
                EnableProfiledAot: false,
                AndroidLinkMode: "None",
                AndroidLinkTool: "r8",
                AndroidDexTool: "d8",
                CreateMappingFile: false,
                EnableMultiDex: false,
                UseAapt2: true,
                EnableDesugar: true,
                IncludeApk: true,
                IncludeAab: false,
                SignMode: "Auto",
                Configuration: "Release"),

            _ => new PlatformProfile(
                TargetFramework: "net10.0",
                RuntimeIdentifier: "osx-arm64",
                SelfContained: true,
                PublishTrimmed: false,
                PublishAot: false,
                PublishReadyToRun: false,
                PublishSingleFile: true,
                UseAppHost: true,
                CreateMacAppBundle: true,
                CreateWindowsExecutable: true,
                BuildIpa: false,
                ArchiveOnBuild: true,
                RunAotCompilation: false,
                EnableProfiledAot: false,
                AndroidLinkMode: "None",
                AndroidLinkTool: "r8",
                AndroidDexTool: "d8",
                CreateMappingFile: false,
                EnableMultiDex: false,
                UseAapt2: true,
                EnableDesugar: true,
                IncludeApk: true,
                IncludeAab: false,
                SignMode: "Auto",
                Configuration: "Release")
        };
    }

    public static bool IsMacCatalyst(string targetFramework, string runtimeIdentifier)
    {
        return targetFramework.Contains("maccatalyst", StringComparison.OrdinalIgnoreCase)
            || runtimeIdentifier.Contains("maccatalyst", StringComparison.OrdinalIgnoreCase);
    }
}
